### ISSUE TITLE
Create Readme file

### ISSUE THREAD

**Issue by mrabdullahdev** [Jadugars/versity#3]
Add readme file to have better understanding of the project for viewers.

**Comment by 96RadhikaJadhav** [comment]
@mrabdullahdev  I can add a Readme file where the steps on how to fork, clone a repo and to create a PR will be given. Can I work on it?

**Comment by kronaemmanuel** [comment]
@96RadhikaJadhav that would be great

**Comment by 96RadhikaJadhav** [comment]
@kronaemmanuel  I have created a PR. Could you please review it.

**Comment by kronaemmanuel** [comment]
@96RadhikaJadhav Kindly check the PR for the changes requested. Thanks a lot for helping our Open Source project.
